version: "3"
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
  php:
    image: php:fpm
    volumes:
      - .:/var/www/html
  composer:
    image: composer
    volumes:
      - .:/app
